version: '3.8'

services:
  class_room_db:
    image: mysql:8.0
    container_name: mysql_classroom
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classroom_reservations
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    user: "mysql"

volumes:
  mysql_data:
    driver: local
